name: Develop CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleNormalRelease assembleCompatibleRelease -Pversion=${{ github.ref_name }}

      - name: Sign Normal APK
        id: sign_normal_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/normal/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY /u3+7QAAAAIAAAABAAAAAQAEc2FtZQAAAZZDh+31AAAFAjCCBP4wDgYKKwYBBAEqAhEBAQUABIIE6gKDc7CQz7s2ZRwHJWbtW6c/lX2c0QB2nHcaLaymRkxVWHCU3AjehwDCS9bZEogR7cRsQKmpajTAypI7SBPQIS7XfRex9Y+v58uBBLQB/ThaEZVYOlX2MzalY9YbbHG2lgxO6Ci8ElakUMeKuxq9gg9F6bGz0MCkKtZW2QGj7AEWQu6/SnSIprUxykxWVfSvB5ZTPPM+KT1vM94AnclFO3R5J5HB3EBUZgii7xi85dqz/K573gdyXZqrmHbqKITdNKvPFUiDudhj/B/YLpHxoxX47ySB5ZRHj9Q1w3lf23tf6JUG87ft6k0cBFILK749GFNE6bh7k5ixQhyEABplBI07dbskE+f8uN1iPpY9DAI04z9syoSbg8ws70U/MbdS3EXGS6FKtkiV3TeF8MHZSy93rehoqcVgd0SYpG7HUP6BUbE3ebIF2SlWepPx/qKEc5bf9ALmztth+lzG3kIhMOD0Dyo2sThVHxZlXqXhhuCxCop0SULOKVJjvMIogY5s/2ZxkoAXcEp32Z10PURkVHN52dE6V2ni84gBK3EWHAaf3nRCa8wf6wNB2PDV/w4gW6CZJyOhWmOuVLxyJkOtSpPcjoVGhkXSg4J4vnYiybst/ZpKsQ6TAozVZLCn1ftRE/Ef5Q3Wt3VOmxNHimfsHo2lQ/ULe446WlZ1e37AX5IDolT7B+jRH5sBBkFJqP5t22x0FlzalKRi39JSbRFuQdZCOck/JKPc0+dU4kwSAVfLkltSmekbnzRMwm8/2iiXyCM1YaYBthLDKpmv21zuoIZau9ciua7rpMGulisF18YjGAAqH2nSBpWbUONerTdbvIAbUkLeyhQUYygTBzLiYqF2/Q8fD7u1KxYcQTQQDn7C3+7Z7UYLFgC9KlDoXIRdVSnRDb+Y0+n76hCyGTbkmMNbWe9xaUS7wyHR6YtIJ5zuqQfGHJSkelivYCryJLvMZBS2aca2jAg2xpFXZsjeV4ZbySuqId6vgWc6It+n3p/H+XJ11kg4FBbcPxnWBcKcdIG0TQ81xk7Q0zn2RRGMU3mHWq6JtbqoRf1Z5BF776QZq+OwPihGZYSC6sih1cRCkHi3evOE7JRw66D1PNAZv407tAnm5Fit4BjgjpHl2/hc0PSy8HoX5rHGi77hNiHQO+j7KLQi77flZj13A70eGNv1CUhpXgRhu8BjdxoL7CxQfE7WkAqP2UIi8Z5Up5RbzJZyYZ+aN4ueYSlyJNuK5oaM3xylloU8/W4NeAy7xTqy49Qx4KyhnOh4kK4mZHQHwxvWhWfe9PoND8OEjhiBM+KycMCMYrWh0VkIX4Aum3PaXHMiFdSVvZm5vyUjRQi4BL4JD677i18V3IOlZpek+6tigYWMRPqHB1TQTz/GHouNXnZ5gRGmA3LxnXBHL1rLh1Yx6CPZLMyGwdIjOe/aULeCLoLofMCTbH/cJBJyL+aADBWiUd8rxCyaWbC6NarD1QsZNMJ5w2CedHpyoARX8Ky7O8iF9CoRPiWcEpWeuroGPx3P1Gy7TV838IGHNSNbfliOI0p36O711JUmVd+H4M98AGb3C3bjVkTHk6Jh3bY6OjsRFYKdFyyteqvjE0O0OoLHswPkdzOddYVaSBOiCjmQm4kYBIC6qkPc7PJaKZ7zm/b22RXpKGFyK7kdneMNdXulDm1l1aR05HAAAAABAAVYLjUwOQAAApwwggKYMIIBgKADAgECAgQs7T2XMA0GCSqGSIb3DQEBCwUAMA0xCzAJBgNVBAYTAkNOMCAXDTI1MDQxNzExMzUwM1oYDzIwNTAwNDExMTEzNTAzWjANMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKWnl+OJirDg0UpcAxYntoY5ED0Sh389lDvO8W93cMnp3vM63/qWf+iAAHi6gNm0Eho1PxthGYyZFj7vlIC2Xuk+BN8nDE52vVGRkav+99T46HN1J7TZySOPmIQZuOVdGkBYTSO+oWXqn3wDYD2Tj6XwCUr67m/n6X/pjyalrXhQLnuPjzOu8+kt0NxOqKe+74AUcpz/QZezhhM92CkDqHVy8obmJOGd1zFIOAkg1qLr0MNB2oZ3YAWCDgpLps7FWYpvbeSKiszdaV8SFY0FriBXPV7khcx6rBmX71dZteOxUz333wtd4lv2WcCExRyukCCv2cOZQqUyemi4grT1HRECAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAW0T+Q8X1Wmods0fzgWHMVMSKJ44yhn5YZyewgK+LgRFkD+lGy7O8krN68UBK5uN4OVdi+77UUJdNUVMsNOUouM+S99JgM3513THoRDPGNkIOImh8lba09z6VV/H8jAVpTkLLvjovd0i4nVnpLyuTnosXXNOJRNteOqn52XRRtIRAz2V2aTeen/zgBe9dH6EL0ZqrC5uHutx8Y+20N5whlzpMPAD/5SzyDtNl5f8Ao7LAJNvvSYg0tYUbDH/6BkOw5vMLfHRre+/yGwDjdPDMo7fkaF57brlgNkd6n9H3ILaw8Udnn7pUbEB8kVoC4F/lpFafuhnEhwy8prJ1psU8bdYqKlE7YYJA8lZcheECkDXQ4vJP}}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS same}}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD 123456}}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Sign Compatible APK
        id: sign_compatible_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/compatible/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY /u3+7QAAAAIAAAABAAAAAQAEc2FtZQAAAZZDh+31AAAFAjCCBP4wDgYKKwYBBAEqAhEBAQUABIIE6gKDc7CQz7s2ZRwHJWbtW6c/lX2c0QB2nHcaLaymRkxVWHCU3AjehwDCS9bZEogR7cRsQKmpajTAypI7SBPQIS7XfRex9Y+v58uBBLQB/ThaEZVYOlX2MzalY9YbbHG2lgxO6Ci8ElakUMeKuxq9gg9F6bGz0MCkKtZW2QGj7AEWQu6/SnSIprUxykxWVfSvB5ZTPPM+KT1vM94AnclFO3R5J5HB3EBUZgii7xi85dqz/K573gdyXZqrmHbqKITdNKvPFUiDudhj/B/YLpHxoxX47ySB5ZRHj9Q1w3lf23tf6JUG87ft6k0cBFILK749GFNE6bh7k5ixQhyEABplBI07dbskE+f8uN1iPpY9DAI04z9syoSbg8ws70U/MbdS3EXGS6FKtkiV3TeF8MHZSy93rehoqcVgd0SYpG7HUP6BUbE3ebIF2SlWepPx/qKEc5bf9ALmztth+lzG3kIhMOD0Dyo2sThVHxZlXqXhhuCxCop0SULOKVJjvMIogY5s/2ZxkoAXcEp32Z10PURkVHN52dE6V2ni84gBK3EWHAaf3nRCa8wf6wNB2PDV/w4gW6CZJyOhWmOuVLxyJkOtSpPcjoVGhkXSg4J4vnYiybst/ZpKsQ6TAozVZLCn1ftRE/Ef5Q3Wt3VOmxNHimfsHo2lQ/ULe446WlZ1e37AX5IDolT7B+jRH5sBBkFJqP5t22x0FlzalKRi39JSbRFuQdZCOck/JKPc0+dU4kwSAVfLkltSmekbnzRMwm8/2iiXyCM1YaYBthLDKpmv21zuoIZau9ciua7rpMGulisF18YjGAAqH2nSBpWbUONerTdbvIAbUkLeyhQUYygTBzLiYqF2/Q8fD7u1KxYcQTQQDn7C3+7Z7UYLFgC9KlDoXIRdVSnRDb+Y0+n76hCyGTbkmMNbWe9xaUS7wyHR6YtIJ5zuqQfGHJSkelivYCryJLvMZBS2aca2jAg2xpFXZsjeV4ZbySuqId6vgWc6It+n3p/H+XJ11kg4FBbcPxnWBcKcdIG0TQ81xk7Q0zn2RRGMU3mHWq6JtbqoRf1Z5BF776QZq+OwPihGZYSC6sih1cRCkHi3evOE7JRw66D1PNAZv407tAnm5Fit4BjgjpHl2/hc0PSy8HoX5rHGi77hNiHQO+j7KLQi77flZj13A70eGNv1CUhpXgRhu8BjdxoL7CxQfE7WkAqP2UIi8Z5Up5RbzJZyYZ+aN4ueYSlyJNuK5oaM3xylloU8/W4NeAy7xTqy49Qx4KyhnOh4kK4mZHQHwxvWhWfe9PoND8OEjhiBM+KycMCMYrWh0VkIX4Aum3PaXHMiFdSVvZm5vyUjRQi4BL4JD677i18V3IOlZpek+6tigYWMRPqHB1TQTz/GHouNXnZ5gRGmA3LxnXBHL1rLh1Yx6CPZLMyGwdIjOe/aULeCLoLofMCTbH/cJBJyL+aADBWiUd8rxCyaWbC6NarD1QsZNMJ5w2CedHpyoARX8Ky7O8iF9CoRPiWcEpWeuroGPx3P1Gy7TV838IGHNSNbfliOI0p36O711JUmVd+H4M98AGb3C3bjVkTHk6Jh3bY6OjsRFYKdFyyteqvjE0O0OoLHswPkdzOddYVaSBOiCjmQm4kYBIC6qkPc7PJaKZ7zm/b22RXpKGFyK7kdneMNdXulDm1l1aR05HAAAAABAAVYLjUwOQAAApwwggKYMIIBgKADAgECAgQs7T2XMA0GCSqGSIb3DQEBCwUAMA0xCzAJBgNVBAYTAkNOMCAXDTI1MDQxNzExMzUwM1oYDzIwNTAwNDExMTEzNTAzWjANMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKWnl+OJirDg0UpcAxYntoY5ED0Sh389lDvO8W93cMnp3vM63/qWf+iAAHi6gNm0Eho1PxthGYyZFj7vlIC2Xuk+BN8nDE52vVGRkav+99T46HN1J7TZySOPmIQZuOVdGkBYTSO+oWXqn3wDYD2Tj6XwCUr67m/n6X/pjyalrXhQLnuPjzOu8+kt0NxOqKe+74AUcpz/QZezhhM92CkDqHVy8obmJOGd1zFIOAkg1qLr0MNB2oZ3YAWCDgpLps7FWYpvbeSKiszdaV8SFY0FriBXPV7khcx6rBmX71dZteOxUz333wtd4lv2WcCExRyukCCv2cOZQqUyemi4grT1HRECAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAW0T+Q8X1Wmods0fzgWHMVMSKJ44yhn5YZyewgK+LgRFkD+lGy7O8krN68UBK5uN4OVdi+77UUJdNUVMsNOUouM+S99JgM3513THoRDPGNkIOImh8lba09z6VV/H8jAVpTkLLvjovd0i4nVnpLyuTnosXXNOJRNteOqn52XRRtIRAz2V2aTeen/zgBe9dH6EL0ZqrC5uHutx8Y+20N5whlzpMPAD/5SzyDtNl5f8Ao7LAJNvvSYg0tYUbDH/6BkOw5vMLfHRre+/yGwDjdPDMo7fkaF57brlgNkd6n9H3ILaw8Udnn7pUbEB8kVoC4F/lpFafuhnEhwy8prJ1psU8bdYqKlE7YYJA8lZcheECkDXQ4vJP}}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS same}}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD 123456}}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD 123456}}
          buildToolsVersion: 34.0.0

      - name: Upload Sesame compatible
        uses: actions/upload-artifact@v4
        with:
          name: apk-compatible
          path: "./app/build/outputs/apk/compatible/release/*signed.apk"

      - name: Upload Sesame normal
        uses: actions/upload-artifact@v4
        with:
          name: apk-normal
          path: "./app/build/outputs/apk/normal/release/*signed.apk"
